### ISSUE TITLE
KeyError: 'backbone.conv.conv.weight'

### ISSUE THREAD

**Issue by seekingdeep** [frotms/PaddleOCR2Pytorch#1]
```
python ./converter/ch_ppocr_mobile_v2.0_det_converter.py --src_model_path ./ch_ppocr_mobile_v2.0_det_infer/
{'k': 50, 'in_channels': 96}
paddle weights loading...
Traceback (most recent call last):
  File "./converter/ch_ppocr_mobile_v2.0_det_converter.py", line 61, in <module>
    converter = MobileV20DetConverter(cfg, paddle_pretrained_model_path)
  File "./converter/ch_ppocr_mobile_v2.0_det_converter.py", line 13, in __init__
    self.load_paddle_weights(paddle_pretrained_model_path)
  File "./converter/ch_ppocr_mobile_v2.0_det_converter.py", line 43, in load_paddle_weights
    self.net.state_dict()[k].copy_(torch.Tensor(para_state_dict[ppname]))
KeyError: 'backbone.conv.conv.weight'
```

**Comment by frotms** [comment]
> ```
> python ./converter/ch_ppocr_mobile_v2.0_det_converter.py --src_model_path ./ch_ppocr_mobile_v2.0_det_infer/
> {'k': 50, 'in_channels': 96}
> paddle weights loading...
> Traceback (most recent call last):
>   File "./converter/ch_ppocr_mobile_v2.0_det_converter.py", line 61, in <module>
>     converter = MobileV20DetConverter(cfg, paddle_pretrained_model_path)
>   File "./converter/ch_ppocr_mobile_v2.0_det_converter.py", line 13, in __init__
>     self.load_paddle_weights(paddle_pretrained_model_path)
>   File "./converter/ch_ppocr_mobile_v2.0_det_converter.py", line 43, in load_paddle_weights
>     self.net.state_dict()[k].copy_(torch.Tensor(para_state_dict[ppname]))
> KeyError: 'backbone.conv.conv.weight'
> ```
use `ch_ppocr_mobile_v2.0_det_train` instead of ch_ppocr_mobile_v2.0_det_infer.

**Comment by frotms** [comment]
@seekingdeep use ch_ppocr_mobile_v2.0_det_train instead of ch_ppocr_mobile_v2.0_det_infer.

**Comment by seekingdeep** [comment]
`ch_ppocr_server_v2.0_det_train`
```
python ./converter/ch_ppocr_server_v2.0_det_converter.py --src_model_path ./ch_ppocr_server_v2.0_det_train/
{'k': 50, 'in_channels': 256}
todo
Traceback (most recent call last):
  File "./converter/ch_ppocr_server_v2.0_det_converter.py", line 67, in <module>
    image = cv2.resize(image, (320, 448))
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

`ch_ppocr_mobile_v2.0_det_train`
```
python ./converter/ch_ppocr_server_v2.0_det_converter.py --src_model_path ./ch_ppocr_mobile_v2.0_det_train/
{'k': 50, 'in_channels': 256}
Traceback (most recent call last):
  File "./converter/ch_ppocr_server_v2.0_det_converter.py", line 63, in <module>
    converter = ServerV20DetConverter(cfg, paddle_pretrained_model_path)
  File "./converter/ch_ppocr_server_v2.0_det_converter.py", line 12, in __init__
    self.load_paddle_weights(paddle_pretrained_model_path)
  File "./converter/ch_ppocr_server_v2.0_det_converter.py", line 46, in load_paddle_weights
    self.net.state_dict()[k].copy_(torch.Tensor(para_state_dict[ppname]))
KeyError: 'backbone.conv1_1._conv.weight'
```

**Comment by frotms** [comment]
@seekingdeep what is your input image?

**Comment by seekingdeep** [comment]
i still didn't use any input images, i am trying to convert the model to .pth so i can later use it to predict.

**Comment by frotms** [comment]
just comment inferernce phace code [here](https://github.com/frotms/PaddleOCR2Pytorch/blob/main/converter/ch_ppocr_mobile_v2.0_det_converter.py#L65)

**Comment by frotms** [comment]
raise cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by seekingdeep** [comment]
Thanks, it's working now
