### ISSUE TITLE
GRUCell模块转写bias问题

### ISSUE THREAD

**Issue by SWHL** [frotms/PaddleOCR2Pytorch#11]
- 感谢作者的工作，正好看到一个小问题
- 下面是作者转写的，其中`bias=True`
https://github.com/frotms/PaddleOCR2Pytorch/blob/28ac1197325dff63f084b845fe82b92cab04e921/pytorchocr/modeling/heads/rec_att_head.py#L76-L77

- Paddle系列写法[源码](https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/ppocr/modeling/heads/rec_att_head.py#L89-L90)
```python
        self.rnn = nn.GRUCell(input_size=input_size + num_embeddings, hidden_size=hidden_size)
```
- 经过查各自API，发现Paddle中的[GRUCell](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/GRUCell_cn.html#grucell)，`bias`默认为`None`，作者转写对应`GRUCell`设置为`bias=True`
- 不知是您笔误，还是有其他用法

**Comment by frotms** [comment]
> * 感谢作者的工作，正好看到一个小问题
> * 下面是作者转写的，其中`bias=True`
>   https://github.com/frotms/PaddleOCR2Pytorch/blob/28ac1197325dff63f084b845fe82b92cab04e921/pytorchocr/modeling/heads/rec_att_head.py#L76-L77
> * Paddle系列写法[源码](https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/ppocr/modeling/heads/rec_att_head.py#L89-L90)
> 
> ```python
>         self.rnn = nn.GRUCell(input_size=input_size + num_embeddings, hidden_size=hidden_size)
> ```
> 
> * 经过查各自API，发现Paddle中的[GRUCell](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/GRUCell_cn.html#grucell)，`bias`默认为`None`，作者转写对应`GRUCell`设置为`bias=True`
> * 不知是您笔误，还是有其他用法

 @SWHL 感谢提问。paddle的GRUCell是

```class paddle.nn.GRUCell(input_size, hidden_size, weight_ih_attr=None, weight_hh_attr=None, bias_ih_attr=None, bias_hh_attr=None, name=None)
```

默认weight_*_attr和bias_*_attr均为None，不代表它的weight和bias为None或False。
根据[GRUCell源码](https://github.com/PaddlePaddle/Paddle/blob/release/2.1/python/paddle/nn/layer/rnn.py#L543)：

```
self.weight_* = self.create_parameter(
            (3 * hidden_size, hidden_size),
            weight_*_attr,
            default_initializer=I.Uniform(-std, std))
self.bias_* = self.create_parameter(
            (3 * hidden_size, ),
            bias_*_attr,
            is_bias=True,
            default_initializer=I.Uniform(-std, std))
```

有[create_parameter](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#create_parameter)初始化weight和bias的，默认值为None，表示将采用 ParamAttr 的默认方式初始化。

**Comment by SWHL** [comment]
感谢，知道了，你是正确的
