### ISSUE TITLE
可以提供转onnx的脚本吗

### ISSUE THREAD

**Issue by huaxiangwangman** [frotms/PaddleOCR2Pytorch#13]

**Comment by frotms** [comment]
您可以自行添加，先加载模型，再用`torch.onnx.export`就可以正常导出

**Comment by huaxiangwangman** [comment]
请问轻量级检测模型的输入尺寸是多少呢

**Comment by frotms** [comment]
默认检测是`[bs, 3, 640, 640]`，识别是`[bs, 3, 32, 320]`

**Comment by huaxiangwangman** [comment]
好的谢谢您!,祝福您生活愉快

**Comment by Gotta-C** [comment]
torch.onnx.export，网络部分是怎么加载的

**Comment by Gotta-C** [comment]
> 请问轻量级检测模型的输入尺寸是多少呢

你转成功了么？

**Comment by zhangxiaopang88** [comment]
请问转的时候网络文件是自己编写吗，权重有了，但是没网络文件
