### ISSUE TITLE
大佬，V2大概多久能搞出来

### ISSUE THREAD

**Issue by GuardSkill** [frotms/PaddleOCR2Pytorch#14]
大佬，V2大概多久能搞出来

**Comment by frotms** [comment]
@GuardSkill 不好意思，最近比较忙，可能要这周末或者下周弄了

**Comment by frotms** [comment]
@GuardSkill V2已更新

**Comment by GuardSkill** [comment]
厉害 非常感谢 ---- 回复的原邮件 ***@***.***>发送日期2021年09月11日 12:18 ***@***.***> ***@***.******@***.***>主题Re: [frotms/PaddleOCR2Pytorch] 大佬，V2大概多久能搞出来 (#14)

@GuardSkill V2已更新



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/frotms/PaddleOCR2Pytorch/issues/14#issuecomment-917336407",

"url": "https://github.com/frotms/PaddleOCR2Pytorch/issues/14#issuecomment-917336407",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
