### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by johnnnya** [frotms/PaddleOCR2Pytorch#2]
大佬有想写训练部分的代码吗

**Comment by frotms** [comment]
@johnnnya 暂时没有考虑一嫖到底

**Comment by renmada** [comment]
> @johnnnya 暂时没有考虑一嫖到底
infer的权重可以用来训练吗

**Comment by frotms** [comment]
> > @johnnnya 暂时没有考虑一嫖到底
> > infer的权重可以用来训练吗

@renmada 有训练代码就可以
