### ISSUE TITLE
paddleocr trained model to pytorch pth.

### ISSUE THREAD

**Issue by Ehteshamciitwah** [frotms/PaddleOCR2Pytorch#20]
Hello, thank you for your work. 
I trained SRN mudule in PaddleOCR on my dataset. i convert the trained model into inference and onnxt format. How can i convert trained model to pytorch pth file. 
Thank you

**Comment by frotms** [comment]
> Hello, thank you for your work. I trained SRN mudule in PaddleOCR on my dataset. i convert the trained model into inference and onnxt format. How can i convert trained model to pytorch pth file. Thank you

@Ehteshamciitwah 
You can try:
`python ./converter/srn_converter.py --yaml_path ./configs/rec/rec_r50_fpn_srn.yml --src_model_path your_ppocr_rec_r50_vd_srn_train_dir`
when [rec_r50_fpn_srn.yml](https://github.com/frotms/PaddleOCR2Pytorch/blob/main/configs/rec/rec_r50_fpn_srn.yml) has same architecture with [trained model](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/configs/rec/rec_r50_fpn_srn.yml).

**Comment by GanWang** [comment]
亮眼的工作，这是我第一次看到的paddle到torch的模型转换，佩服！

**Comment by GanWang** [comment]
顺便说一句：PaddleOCR模型百度网盘链接：https://pan.baidu.com/s/1getAprT2l_JqwhjwML0g9g 提取码：lmv7这个链接无效了~~
