### ISSUE TITLE
转换pt模型报错

### ISSUE THREAD

**Issue by changxinC** [frotms/PaddleOCR2Pytorch#21]
python ./converter/ch_ppocr_v2_rec_converter.py --src_model_path ./ch_PP-OCRv2_rec_train
文件路径：ch_PP-OCRv2_rec_train/best_accuracy/**.pdopt、**.pdparams、**.states
完整报错如下：
W1223 17:12:03.727869 23403 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W1223 17:12:03.732515 23403 device_context.cc:422] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "./converter/ch_ppocr_v2_rec_converter.py", line 80, in <module>
    converter = PPOCRv2RecConverter(cfg, paddle_pretrained_model_path)
  File "./converter/ch_ppocr_v2_rec_converter.py", line 12, in __init__
    para_state_dict, opti_state_dict = self.read_paddle_weights(paddle_pretrained_model_path)
  File "/data/cxchen/PaddleOCR2Pytorch/pytorchocr/base_ocr_v20.py", line 94, in read_paddle_weights
    para_state_dict, opti_state_dict = fluid.load_dygraph(weights_path)
  File "/data/cxchen/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/checkpoint.py", line 290, in load_dygraph
    attrs={'file_path': os.path.join(model_path, name)})
  File "/data/cxchen/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1904018048 found).
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)
  [operator < load > error]

**Comment by frotms** [comment]
paddlepaddle是什么版本的？需要>=2.0以上。你用`paddle.fluid.load_dygraph("./ch_PP-OCRv2_rec_train/best_accuracy")`试一下看看能不能读出模型

**Comment by changxinC** [comment]
> paddlepaddle是什么版本的？需要>=2.0以上。你用`paddle.fluid.load_dygraph("./ch_PP-OCRv2_rec_train/best_accuracy")`试一下看看能不能读出模型

paddle是2.1.3版本的，用上述命令读不出模型，报一样的错

**Comment by frotms** [comment]
OCRv2_rec_train里面是best_accuracy.pdopt, best_accuracy.pdparams, best_accuracy.states吗? 有可能是模型的问题，下载不全之类的

**Comment by changxinC** [comment]
> OCRv2_rec_train里面是best_accuracy.pdopt, best_accuracy.pdparams, best_accuracy.states吗? 有可能是模型的问题，下载不全之类的

我路径弄错了，OCRv2_rec_train里还有一个best_accuracy的文件夹。按你说的修改后已解决问题，谢谢
