### ISSUE TITLE
TPS and Transform support using PyTorch Code

### ISSUE THREAD

**Issue by kunaljain0** [frotms/PaddleOCR2Pytorch#3]
@frotms, I tried the Paddle code for conversion of TPS based models, the model gets converted but causes problems during the inference. Can you add support for TPS based models conversion using PyTorch?

**Comment by frotms** [comment]
Hi, @kunaljain0,
I'll try to add TPS-based models and other PaddleOCRv2.0 models in next few months.
Or you could share your code or problems here.

**Comment by kunaljain0** [comment]
@frotms, This is the error that I get when I run the predict_rec.py script (at line number 146) `rec_res, predict_time = text_recognizer(img_list)`

`ValueError: (InvalidArgument) conv2d(): argument 'Input' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function.h:56)`

Thanks

**Comment by frotms** [comment]
@kunaljain0 It seems like a type error. Is there any more information? Could you offer a TPS-based model? I can't find inference and trained TPS-based models in PaddleOCR.

**Comment by kunaljain0** [comment]
[rec_mv3_tps_bilstm_ctc.zip](https://github.com/frotms/PaddleOCR2Pytorch/files/6209780/rec_mv3_tps_bilstm_ctc.zip)
@frotms, I've attached the PyTorch model which was converted using the conversion script. I think it could be because of the fact that conversion script uses PyTorch and TPS script uses Paddle framework. 
Thanks

**Comment by frotms** [comment]
@kunaljain0 I cannot find any weights of TPS in mv3_rec_tps_ctc.pth when using torch.load only. Maybe there is something wrong with conversion in TPS.

**Comment by kunaljain0** [comment]
@frotms, yes, there's something wrong with the conversion. Looks like things should be changed in the conversion code as well. Thanks.

**Comment by frotms** [comment]
> @frotms, yes, there's something wrong with the conversion. Looks like things should be changed in the conversion code as well. Thanks.

@kunaljain0, 
I found a bug in the conversion from paddleOCR trained model to inference model. 
The trained model was trained by
<img width="190" alt="微信图片_20210412221031" src="https://user-images.githubusercontent.com/18061450/114408405-f2e26b00-9bdb-11eb-8212-1c7ac66024b2.png">


but the configuration in [configs/rec/rec_r34_vd_tps_bilstm_ctc.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/configs/rec/rec_r34_vd_tps_bilstm_ctc.yml) is
<img width="178" alt="微信图片_20210412220838" src="https://user-images.githubusercontent.com/18061450/114408106-adbe3900-9bdb-11eb-9705-086ea00566ec.png">

you can see the detail in the train log below.
[train.log](https://github.com/frotms/PaddleOCR2Pytorch/files/6297338/train.log)
