### ISSUE TITLE
使用预训练模型出现 KeyError: 'neck.in2_conv.weight'

### ISSUE THREAD

**Issue by SouthIO** [frotms/PaddleOCR2Pytorch#34]
使用的模型结构是 ./configs/det/det_r50_vd_db.yml ，使用的paddle参数文件下载自 https://paddleocr.bj.bcebos.com/pretrained/ResNet50_vd_ssld_pretrained.pdparams
但是在尝试模型转换时出现了如下报错
Traceback (most recent call last):
  File "../converter/det_converter.py", line 94, in <module>
    converter = DetV20DetConverter(cfg, paddle_pretrained_model_path, **kwargs)
  File "../converter/det_converter.py", line 12, in __init__
    self.load_paddle_weights(paddle_pretrained_model_path)
  File "../converter/det_converter.py", line 56, in load_paddle_weights
    self.net.state_dict()[k].copy_(torch.Tensor(para_state_dict[ppname]))
KeyError: 'neck.in2_conv.weight'
原本猜测是模型不对，想要从给的百度网盘中找合适的模型参数文件，但是本项目中提到的网盘链接（https://pan.baidu.com/s/1getAprT2l_JqwhjwML0g9g 提取码：lmv7）已经失效。

**Comment by frotms** [comment]
试一下加上yaml_path参数：
`python3 ./converter/det_converter.py --yaml_path ./configs/det/det_r50_vd_db.yml --src_model_path your_ppocr_det_r50_vd_db_v2.0_train_dir`

**Comment by SouthIO** [comment]
可能是我没有表述清楚，实际上我就是使用的这样的指令，yaml的参数为./configs/det/det_r50_vd_db.yml，然后最后的paddle参数的路径使用的是https://paddleocr.bj.bcebos.com/pretrained/ResNet50_vd_ssld_pretrained.pdparams的参数，更名为best_accuracy

**Comment by SouthIO** [comment]
> 试一下加上yaml_path参数： `python3 ./converter/det_converter.py --yaml_path ./configs/det/det_r50_vd_db.yml --src_model_path your_ppocr_det_r50_vd_db_v2.0_train_dir`

可能是我没有表述清楚，实际上我就是使用的这样的指令，yaml的参数为./configs/det/det_r50_vd_db.yml，然后最后的paddle参数的路径使用的是https://paddleocr.bj.bcebos.com/pretrained/ResNet50_vd_ssld_pretrained.pdparams的参数，更名为best_accuracy

**Comment by SouthIO** [comment]
已解决，需要先在paddleocr里先进行一遍训练，不能直接使用预训练的模型进行转换
