### ISSUE TITLE
使用SRN识别模型出错

### ISSUE THREAD

**Issue by loveq007** [frotms/PaddleOCR2Pytorch#35]
使用SRN模型识别时，在rec_postprocess.py文件报错：
![2022_05_27_16_37_11](https://user-images.githubusercontent.com/5405492/170663452-da18da25-dfcd-4465-8b42-123bc3de7345.jpg)
看起来是字典不对？我用的是ppocr_keys_v1.txt这个字典。
附rec参数：
# params for text recognizer
    parser.add_argument("--rec_algorithm", type=str, default='SRN')
    parser.add_argument("--rec_model_path", type=str, default='./weights/rec_r50_vd_srn_infer.pth')
    parser.add_argument("--rec_image_shape", type=str, default="1, 64, 256")
    parser.add_argument("--rec_char_type", type=str, default='en')
    parser.add_argument("--rec_batch_num", type=int, default=6)
    parser.add_argument("--max_text_length", type=int, default=25)
parser.add_argument("--use_space_char", type=str2bool, default=True)
    parser.add_argument("--drop_score", type=float, default=0.5)
    parser.add_argument("--limited_max_width", type=int, default=1280)
    parser.add_argument("--limited_min_width", type=int, default=16)

    parser.add_argument(
        "--vis_font_path", type=str,
        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'doc/fonts/simfang.ttf'))
    parser.add_argument(
        "--rec_char_dict_path",
        type=str,
        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                             'pytorchocr/utils/ppocr_keys_v1.txt'))
# params .yaml
    parser.add_argument("--det_yaml_path", type=str, default=None)
    parser.add_argument("--rec_yaml_path", type=str, default="./configs/rec/rec_r50_fpn_srn.yml")
    parser.add_argument("--cls_yaml_path", type=str, default=None)
    parser.add_argument("--e2e_yaml_path", type=str, default=None)

**Comment by frotms** [comment]
@loveq007 字典使用不对。试试：
`python ./tools/infer/predict_rec.py --rec_model_path rec_r50_vd_srn_infer.pth --rec_image_shape 1,64,256 --rec_algorithm SRN --rec_yaml_path ./configs/rec/rec_r50_fpn_srn.yml --rec_char_dict_path ./pytorchocr/utils/ic15_dict.txt
--use_space_char false --image_dir ./doc/imgs_words_en/word_461.png `

**Comment by loveq007** [comment]
问题解决了，非常感谢！
