### ISSUE TITLE
ppocr-v3中文识别模型预测结果与paddle的不一致

### ISSUE THREAD

**Issue by zhiweizhong** [frotms/PaddleOCR2Pytorch#49]
请问下对pytorch版本有要求吗？我使用ch_ptocr_v3_rec_infer.pth的识别结果：

```
python ./tools/infer/predict_rec.py --rec_algorithm SVTR --rec_model_path ./ch_ptocr_v3_rec_infer.pth --rec_image_shape 3,48,320 --image_dir test.jpg

('注室你的以发一夜七发使用4突击步检命中头部海淡了', 0.74806666)
```

以下是paddleocr的识别结果：

```
paddleocr --image_dir  test.jpg --det false

('主室你的队友一液七次i使用AKM突击步枪命中头部淘汰了', 0.9387470483779907)
```
![test](https://user-images.githubusercontent.com/5139074/178108130-e0679505-8d4f-4baf-a2cc-d0b3b832b201.jpg)

**Comment by frotms** [comment]
感谢关注。如果要和PaddleOCR对齐，请使用和PaddleOCR一样的参数即可：
`python ./tools/infer/predict_rec.py --rec_algorithm SVTR_lcnet --rec_model_path ./ch_ptocr_v3_rec_infer.pth --rec_image_shape 3,48,320 --image_dir test.jpg
`
或去掉--rec_algorithm参数)
`python ./tools/infer/predict_rec.py --rec_model_path ./ch_ptocr_v3_rec_infer.pth --rec_image_shape 3,48,320 --image_dir test.jpg`

**Comment by zhiweizhong** [comment]
感谢大佬，结果现在一致了
