### ISSUE TITLE
推理速度很慢

### ISSUE THREAD

**Issue by chenzi** [frotms/PaddleOCR2Pytorch#7]
比PaddleOCR慢太多了，一张图片CPU推理十几秒呀。

**Comment by frotms** [comment]
哪个模型？ @chenzi

**Comment by chenzi** [comment]
ch_ptocr_server_v2.0_det_infer.pth,ch_ptocr_server_v2.0_rec_infer.pth 这两个模型

**Comment by frotms** [comment]
方便提供一下测试图吗 @chenzi

**Comment by chenzi** [comment]
我电脑上面的推理：
![image](https://user-images.githubusercontent.com/5486633/122511305-99624680-d039-11eb-870c-a39943255f59.png)

亚马逊上面使用不使用EI和使用EI图：
![image](https://user-images.githubusercontent.com/5486633/122511422-cadb1200-d039-11eb-8e6f-317dbcf34bfb.png)

![image](https://user-images.githubusercontent.com/5486633/122511631-21485080-d03a-11eb-8ee1-f7165e1b7778.png)

使用Paddle2ONNX转成onnx模型的测试图：
![image](https://user-images.githubusercontent.com/5486633/122511761-5654a300-d03a-11eb-94a0-62db6ec8695a.png)


感觉转pytorch后推理速度明显下降了

**Comment by frotms** [comment]
@chenzi 
我这边的测试结果也是，转pytorch后，CPU推理速度确实明显下降，可以用GPU去推理，GPU不慢的。
或者可以试试`torch.set_num_threads()`，再或者将模型转到onnx。

**Comment by chenzi** [comment]
@frotms 我想用亚马逊的EI加速， 也是GPU，只不过EI是虚拟的GPU，可能是EI不兼容。我用onnx模型使用不了EI推理，我试过了，要报错。

**Comment by chenzi** [comment]
就是这个，https://aws.amazon.com/machine-learning/elastic-inference

**Comment by frotms** [comment]
那要详细去看EI文档了。至少在常规的GPU上推理是正常速度。
