### ISSUE TITLE
文字检测报错

### ISSUE THREAD

**Issue by onlinehuazai** [frotms/PaddleOCR2Pytorch#8]
按照测试的方法来，报错
python3 ./tools/infer/predict_rec.py --image_dir ./doc/imgs_words --model_path your_rec_pth_path.pth

报错:系统错误找不到指定模块

**Comment by frotms** [comment]
@onlinehuazai 有具体的报错信息吗

**Comment by onlinehuazai** [comment]
_lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by frotms** [comment]
@onlinehuazai 这个应该是环境的问题

**Comment by onlinehuazai** [comment]
这个依赖环境是啥，具体的有吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frotms/PaddleOCR2Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frotms/PaddleOCR2Pytorch] 文字检测报错 (#8)





 
@onlinehuazai 这个应该是环境的问题

**Comment by frotms** [comment]
是你电脑python环境的问题，百度搜一下：OSError:` [WinError 126] 找不到指定的模块。

**Comment by onlinehuazai** [comment]
找了一下午了，安装了很多都没用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frotms/PaddleOCR2Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frotms/PaddleOCR2Pytorch] 文字检测报错 (#8)





 
是你电脑python环境的问题，百度搜一下：OSError:` [WinError 126] 找不到指定的模块。

**Comment by frotms** [comment]
重点关注下shapely包

**Comment by onlinehuazai** [comment]
删了，重新下，还是不行，dll也下了很多






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frotms/PaddleOCR2Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 晚上8:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frotms/PaddleOCR2Pytorch] 文字检测报错 (#8)





 
重点关注下shapely包

**Comment by frotms** [comment]
看下[https://github.com/PaddlePaddle/PaddleOCR/issues/212](https://github.com/PaddlePaddle/PaddleOCR/issues/212)
