### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by xmadog** [frotms/PaddleOCR2Pytorch#9]
可以直接训练迁移后的模型吗？

**Comment by frotms** [comment]
@xmadog 只支持将PaddleOCR训练的模型转换到PyTorch，如果要训练需要使用PaddleOCR来训练或者自行搭建PyTorch的训练代码

**Comment by SWHL** [comment]
训练的可以直接使用PaddleOCR，推理可以转为pth或者onnx
如果转为onnx模型推理，可以参考[RapidOCR](https://github.com/RapidAI/RapidOCR)
